# -*- mode: ruby -*-
# vi: set ft=ruby :

#Vagrant.require_version ">= 1.3.5" #Only if you want to use a specific version of Vagrant with a Vagrantfile


# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  #VM1 - cu box version de Ubuntu
  config.vm.define "vm1" do |vm1|
    config.vm.box = "ubuntu/trusty64"
    config.vm.box_version = "20191107.0.0"

    #aloc cate o adresa IP pt fiecare masina in parte
    config.vm.network "private_network", ip: "192.168.50.11", type: "dhcp", adapter: 2
    vm1.vm.hostname = "vm1"

    # Dezactivează firewall pentru a permite ping
    vm1.vm.provision "shell", inline: <<-SHELL
      echo "[VM1] Disabling firewall (ufw)..."
      sudo ufw disable
    SHELL

    vm1.vm.provision "docker" do |d|
      d.pull_images "nginx:latest"
    end
    
    vm1.vm.provision "docker_run", type: "docker" do |d|
      d.name "nginx-container"
      d.image "nginx:latest"
      d.ports ["80:80"]
      d.restart "unless-stopped"
    end

  end

  #VM2 - cu box version de Ubuntu
  config.vm.define "vm2" do |vm2|
    config.vm.box = "ubuntu/trusty64"
    config.vm.box_version = "20191107.0.0"

    #aloc cate o adresa IP pt fiecare masina in parte
    config.vm.network "private_network", ip: "192.168.50.12", type: "dhcp", adapter: 2
    vm2.vm.hostname = "vm2"
  end
  
  #VM3 - cu box version de Ubuntu
  config.vm.define "vm3" do |vm3|
    config.vm.box = "ubuntu/trusty64"
    config.vm.box_version = "20191107.0.0"

    #aloc cate o adresa IP pt fiecare masina in parte
    config.vm.network "private_network", ip: "192.168.50.13", type: "dhcp", adapter: 2
    vm3.vm.hostname = "vm3"
  end

  #VM4 - cu box version de Ubuntu
  config.vm.define "vm4" do |vm4|
    config.vm.box = "ubuntu/trusty64"
    config.vm.box_version = "20191107.0.0"

    #aloc cate o adresa IP pt fiecare masina in parte
    config.vm.network "private_network", ip: "192.168.50.14", type: "dhcp", adapter: 2
    vm4.vm.hostname = "vm4"
  end

  #VM5 - cu box version de Ubuntu
  config.vm.define "vm5" do |vm5|
    config.vm.box = "ubuntu/trusty64"
    config.vm.box_version = "20191107.0.0"

    #aloc cate o adresa IP pt fiecare masina in parte
    config.vm.network "private_network", ip: "192.168.50.15", type: "dhcp", adapter: 2
    vm5.vm.hostname = "vm5"
  end



  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  
  #config.vm.box = "base" #momentan nu am nevoie de varianta base

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Disable the default share of the current code directory. Doing this
  # provides improved isolation between the vagrant box and your host
  # by making sure your Vagrantfile isn't accessible to the vagrant box.
  # If you use this you may want to enable additional shared subfolders as
  # shown above.
  # config.vm.synced_folder ".", "/vagrant", disabled: true

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end

